# 예외 처리
### Kotlin의 예외
구조
- Throwable
   - Error: 시스템에 비정상적인 예외. 예측이 어렵고 복구가 불가능하다
      - Unchecked errors: StackOverflowError, OutOfMemoryError, InternalError, UnknownError
   - Exception: 시스템에서 포착 가능하여 (try-catch) 복구 가능. 예외처리 강제
      - RuntimeException: 런타임시에 발생하는 에러. 
         - Unchecked exceptions
      - Checked exceptions

코틀린에서는 Checked exception에 예외 처리를 강제하지 않는다

try-catch도 표현식이기 때문에 값을 받을 수 있다
```kotlin
val a = try {
        "1111".toInt()
    } catch (e: Exception) {
        println("에러 발생")
    }
```

Nothing 타입
- 항상 예외를 리턴한다는 것을 의미
   ```kotlin
   fun fastFail(message: String): Nothing {
      throw IllegalArgumentException(message)
   }
   ```
- elvis 연산자와 함께 쓰면 nullable type을 nonnull 타입으로 변경할 수 있다
   ```kotin
    val nullable: String? = null
    val nonnull: String = nullable ?: fastFail("is null")
    println(nonnull)
   ```